### ISSUE TITLE
Failed to build on 5.9.10: issue with crc32.h

### ISSUE THREAD

**Issue by Kenivia** [rtlwifi-linux/rtk_wifi_driver_rtl8822ce#4]
Kernel version: `5.9.10-050910-generic`
gcc version: `10.2.0`
Make version: `4.2.1`
Linux distro is Linux Mint 20, but i don't think it matters for this issue

` full output:
$ make all
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.9.10-050910-generic/build M=/home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce  modules
make[1]: Entering directory '/usr/src/linux-headers-5.9.10-050910-generic'
  CC [M]  /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/core/crypto/aes-internal.o
In file included from /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/core/crypto/aes-internal.c:17:
/home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/core/crypto/rtw_crypto_wrap.h:78:44: error: macro "crc32" requires 3 arguments, but only 2 given
   78 | u32 crc32(const u8 *frame, size_t frame_len);
      |                                            ^
In file included from ./include/linux/etherdevice.h:23,
                 from /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/include/osdep_service_linux.h:46,
                 from /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/include/osdep_service.h:53,
                 from /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/include/drv_types.h:27,
                 from /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/core/crypto/rtw_crypto_wrap.h:18,
                 from /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/core/crypto/aes-internal.c:17:
./include/linux/crc32.h:66: note: macro "crc32" defined here
   66 | #define crc32(seed, data, length)  crc32_le(seed, (unsigned char const *)(data), length)
      | 
make[2]: *** [scripts/Makefile.build:283: /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce/core/crypto/aes-internal.o] Error 1
make[1]: *** [Makefile:1784: /home/kenivia/Downloads/installs/Misc/rtk_wifi_driver_rtl8822ce] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.9.10-050910-generic'
make: *** [Makefile:2403: modules] Error 2
`

**error: macro "crc32" requires 3 arguments, but only 2 given**

I'm guessing the `crc32` function was changed in a kernel update, but apparently not: 
`#define crc32(seed, data, length)  crc32_le(seed, (unsigned char const *)(data), length)`
the line referenced in the error stayed the same from 2.6.39 to 5.9.10

https://elixir.bootlin.com/linux/v2.6.39/source/include/linux/crc32.h
https://elixir.bootlin.com/linux/v5.9.10/source/include/linux/crc32.h

Please feel free to correct me and I appreciate any advice!

**Comment by crownclownwl** [comment]
我也遇到这个问题了 请问 如何解决
我是 deepin linux v20, 
5.10.5 的内核
